version: '3'
services:
  postgres:
    image: "postgres:alpine"
    restart: always
    volumes:
     - tome:/var/lib/postgresql/data
    ports:
     - 5432:5432
    environment:
     - POSTGRES_USER=postgres
     - POSTGRES_DB=postgres
    networks:
      static-network:
        ipv4_address: 172.20.0.11
  web:
    build: .
    tty: true
    ports:
     - "4444:4444"
    expose:
     - "4444"
    depends_on:
     - postgres
    restart: always
    networks:
      static-network:
        ipv4_address: 172.20.0.12
    command: python3 main.py
volumes:
  tome: {}
networks:
  static-network:
    ipam:
      driver: default    
      config:
       - subnet: 172.20.0.0/16